### ISSUE TITLE
bugs in the code

### ISSUE THREAD

**Issue by abd-alaz** [adienakhmad/ADS1256#1]
I have explained some issues in the comments, a summary is below:

1. RESETPIN needs to be TRUE so the board will work
2. buffenable if set to TRUE/FALSE, the output will be changed slightly !!! why 
3. increasing the gain, reduces the output value slightly (i.e the error increase with higher gain)
4. single channels are not working (such as AIN0 & AIN_COM), diff channels are working fine

**Comment by adienakhmad** [comment]
1. RESETPIN needs to be pulled HIGH all the time, if you connect RESETPIN to a certain port in Arduino board then yes, `useResetPin` needs to be set to true. You also need to define in `ADS1256.h` which port you connected it into.  I hardwired the reset pin to a constant voltage of 3.3v so it's always HIGH and did not need to set `useResetPin` to true. I think by using the name `useResetPin` I'm phrasing it wrong.

2. By setting `buffenable`, the ADS1256 will increase its input impedance. You can read about this on ADS1256 datasheet page 15.

3. It will depends on your setup, the offset error will be determined by the floor noise after the self-calibration. By increasing the gain, you are also increasing the noise.

4. I can't test it myself since at the moment I have no access to the device, but have you made sure to wire the common input to AINCOM and the single-ended input to AIN0-AIN7.

**Comment by phpkadir** [comment]
thank you very much.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virüs
bulunmuyor. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-11-23 15:07 GMT+03:00 Adien Akhmad <notifications@github.com>:

**Comment by abd-alaz** [comment]
I found another issue which I'm not sure why its happening 

when using only one diff channel (let say IN0 & IN1), I don't need to change the channel every time I need to read, so the loop () contains only:

sensor1 =  adc.read channel();

when I do that , the reading value of the channel reduce by about 2.4% (for the same input voltage at IN0 & IN1) and the speed is so quick. I have measured the time require just to read the channel (@2.5 SPS, slowest speed), its about 160 micro sec (yes mico). Anyhow, the speed is not important now and the accuracy is the main concern.

Any ideas ?
regards

**Comment by adienakhmad** [comment]
If you only use a single channel, leave any unused analog channel floating, don't connect anything to it.

Regarding the data rate, that is weird. I remember my last test result showed that all the data rate matched below 7500 SPS.

**Comment by abd-alaz** [comment]
I've just discovered something regarding my previous question and would like to share 

I've discovered that switching between channel 1 and channel 4 will give accurate readings at channel 1 and matching time for SPS value, I'm not reading or using channel 4.

this is weird but working, the catch in that is the double time required for each reading 
sampling was set on 10 SPS, required time for each reading around 198840 micro sec.

---------------------------------------------------------------------
void loop()
{ 
  adc.waitDRDY();						// wait for DRDY to go low before changing multiplexer register
  adc.setChannel(2,3);					// DOUT arriving here are from MUX AIN0 & AIN1
  sensor1 = adc.readChannel(); 

  adc.waitDRDY();
  adc.setChannel(0,1);					// DOUT arriving here are from MUX AIN6 & AIN7
  
  Serial.println(sensor1,10);
  
}

**Comment by adienakhmad** [comment]
That should not happen, as per table of cycling throughput on the manual, 10SPS should still be 10SPS when multiple channel are cycled.

What board are you using? It's probably the timing

**Comment by abd-alaz** [comment]
something similar to this one, (I got my board form AliExpress)

https://www.dhgate.com/store/product/ads1256-module-24-bit-adc-ad-module-high/404947441.html

**Comment by adienakhmad** [comment]
What arduino board are you using?

**Comment by abd-alaz** [comment]
Arduino Mega2560

**Comment by adienakhmad** [comment]
I pushed my old library to a new branch called `old`.

Can you test using the example provided there?

**Comment by abd-alaz** [comment]
Sorry, testing what ? 
what is the expected change in the new library ?

**Comment by adienakhmad** [comment]
That was the first library I wrote for Arduino Mega 2560 (branch: `old`), then I make few changes to make it work with Arduino Pro Micro (branch: `master`)

If it has different result then this topic is still relevant, there is a bug in my new code.
If it's not it may be your setup.

**Comment by abd-alaz** [comment]
I will check and reply soon
thanks

**Comment by KOUKILEO** [comment]
How do I deal with this problem?
exit status 1
'class ADS1256' has no member named 'readCurrentChannel'
