### ISSUE TITLE
[request] Port to ESP32

### ISSUE THREAD

**Issue by YordanYanakiev** [adienakhmad/ADS1256#3]
If there is possibility it would be awesome to see a port of this library for ESP32.

**Comment by chepo92** [comment]
@YordanYanakiev The library would require some rework as it uses direct port manipulation (it works different for ESP32).

**Comment by Labikettedu08** [comment]
Hi,
Thanks a lot for your work ! 
I've an ESP8266 project pending...
Can I just change the "H" file, adding the SPI ports of my ESP8266 or should I change other things to be able to use your Library ?
See you !

**Comment by chepo92** [comment]
> 
> 
> Hi,
> Thanks a lot for your work !
> I've an ESP8266 project pending...
> Can I just change the "H" file, adding the SPI ports of my ESP8266 or should I change other things to be able to use your Library ?
> See you !

It's not that direct, you also have to rework the ADS1256.cpp as port manipulation in ESP is different, however, we can sacrifice some speed and use Arduino standard digitalWrite and digitalRead pins, also some variable size checking must be done (8 bit registers vs 32 bit)

I will find some time to work in this in a new branch

**Comment by Labikettedu08** [comment]
> It's not that direct, you also have to rework the ADS1256.cpp as port manipulation in ESP is different, however, we can sacrifice some speed and use Arduino standard digitalWrite and digitalRead pins, also some variable size checking must be done (8 bit registers vs 32 bit)
> 
> I will find some time to work in this in a new branch

OK, thanks for your reply. I use an ESP8266 not for the speed, but for the Wifi connection.
I'm doing my own home weather station with a lot of sensors. Thoses are nearly all "Analog". This is why I want to use an ADS1256 compined to an ESP8266 (ESP-07S)
Using an ESP32 (Which have enough ADC for my project) is not a good choice because of energy saving...

**Comment by chepo92** [comment]
I may convert the code to a more cross-board library branch, ESP8266 and ESP32 are quite common now and this lib would be usefull

**Comment by Labikettedu08** [comment]
> I my convert the code to a more cross-board library branch, ESP8266 and ESP32 are quite common now and this lib would be usefull

I've found a pretty documentation that could help you I guess...
https://arduino-esp8266.readthedocs.io/en/latest/libraries.html#spi

It shows the "normal" SPI pins for ESP8266 and also the "hardware" SPI pins...

**Comment by chepo92** [comment]
After some rework, the branch devESP in my fork is compiling in Arduino IDE for ESP8266 and ESP32
I haven't tested it yet as I don't have the sensor with me, but any feedback is welcomed

**Comment by Labikettedu08** [comment]
> After some rework, the branch devESP in my fork is compiling in Arduino IDE for ESP8266 and ESP32
> I haven't tested it yet as I don't have the sensor with me, but any feedback is welcomed

All right ! I will test it soon :) 
Thanks for your job !!!

**Comment by Labikettedu08** [comment]
Hi
Seems that you didn't make the update... Are you sure that you have done it ?

**Comment by chepo92** [comment]
> 
> 
> After some rework, the branch devESP in my fork is compiling in Arduino IDE for ESP8266 and ESP32
> I haven't tested it yet as I don't have the sensor with me, but any feedback is welcomed


**my fork**: https://github.com/chepo92/ADS1256/tree/devESP

**Comment by Labikettedu08** [comment]
Perfect ! 
I will test it as soon as possible !!! One more time : Thanks :+1:

**Comment by Labikettedu08** [comment]
Hi,
Tested on NodeMCU and Wemos D1 Mini Lite... Same issue... Watchdog reset... Here the error code

*****************************************************
Soft WDT reset

 >>>stack>>>

ctx: cont
sp: 3ffffdb0 end: 3fffffc0 offset: 01b0
3fffff60:  3ffe858b 00000001 3ffee28c 40201433  
3fffff70:  3ffe8560 00000000 3ffee258 402014df  
3fffff80:  00002580 0000001c 3ffee28c 3ffee2e4  
3fffff90:  3fffdad0 3ffee258 3ffee28c 4020105b  
3fffffa0:  feefeffe 00000000 3ffee2b4 40202440  
3fffffb0:  feefeffe feefeffe 3ffe84fc 40100515  
 <<<stack<<<
*****************************************************

If I did'nt supply my ADS1256, the initialisation is ok, the we get values... All at 0 
*****************************************************
Starting ADC
ADC Started
0.0000000000	0.0000000000	0.0000000000	0.0000000000
0.0000000000	0.0000000000	0.0000000000	0.0000000000
0.0000000000	0.0000000000	0.0000000000	0.0000000000
0.0000000000	0.0000000000	0.0000000000	0.0000000000
0.0000000000	0.0000000000	0.0000000000	0.0000000000
............
*****************************************************

I will check this issue tomorrow...

**Comment by chepo92** [comment]
I got my ADS1256 breakout board back so i made some test. 
I got ESP8266 running (at least with the examples below), so far this branch should be compatible with any board/architecture that has a SPI library in arduino IDE.
https://github.com/chepo92/ADS1256/tree/devESP
Testing ESP32 is a WIP, which of the 3 SPI in this board is the one used by default in the SPI library ? 

I Also added some simpler examples for basic start, and SPS checking. 
https://github.com/chepo92/ADS1256/tree/NewExamples

**Comment by Trackhe** [comment]
any progress? for esp32

i test https://github.com/chepo92/ADS1256/blob/devESP/examples/ADS1256_Efficient_Input_Cycling/ADS1256_Efficient_Input_Cycling.ino

with ports:

ADC -> esp32
V5 -> V5
GND -> GND
SCLK -> IO14  i convert 5v->3v
DIN -> IO13  i convert 5v->3v
DOUT -> IO12  i convert 5v->3v
DRDY -> IO0
CD -> IO15
POWN -> 5V

probably something is wrong?

**Comment by chepo92** [comment]
Prob. Wiring I cant remember if it was working with ESP32, may give it a try during the week as i have the boards in hand

**Comment by Trackhe** [comment]
@chepo92 thank you. 
i m wondering also where are the #define pinRST  16  pin on the board.

**Comment by chepo92** [comment]
> 
> 
> @chepo92 thank you.
> i m wondering also where are the #define pinRST 16 pin on the board.

maybe in https://github.com/chepo92/ADS1256/blob/devESP/ADS1256.h ?

**Comment by Trackhe** [comment]
yes but on the ADC board is no RST pin.

**Comment by chepo92** [comment]
> 
> 
> yes but on the ADC board is no RST pin.

Oh you meant the typical breakout board?, right it has no Reset pin broken out, this library is for the **ADS1256 chip** (so full functionality of the chip), not the breakout in specific (but are compatible by default) please take a look at the datasheet, ~reset is pin 9 or 15 depending on the package of the chip

**Comment by Trackhe** [comment]
![ads1256-24-bit-8-channel-adc-ad-module-high-precision-adc-data-acquisition (2)](https://user-images.githubusercontent.com/1494328/104787387-a7145700-578f-11eb-8e1a-b5374a6fcec2.jpg)
[ADS1256boardcircuit.pdf](https://github.com/adienakhmad/ADS1256/files/5823337/ADS1256boardcircuit.pdf)

I want to use this board. With an ESP32

**Comment by Trackhe** [comment]
I get it Running. Thank you but i become only 
```
...
Sensor 1: -0.0000005960	Sensor 2: -0.0000005960	Sensor 3: -0.0000005960	Sensor 4: -0.0000005960
Sensor 1: -0.0000005960	Sensor 2: -0.0000005960	Sensor 3: -0.0000005960	Sensor 4: -0.0000005960
Sensor 1: -0.0000005960	Sensor 2: -0.0000005960	Sensor 3: -0.0000005960	Sensor 4: -0.0000005960
Sensor 1: -0.0000005960	Sensor 2: -0.0000005960	Sensor 3: -0.0000005960	Sensor 4: -0.0000005960
Sensor 1: -0.0000005960	Sensor 2: -0.0000005960	Sensor 3: -0.0000005960	Sensor 4: -0.0000005960
Sensor 1: -0.0000005960	Sensor 2: -0.0000005960	Sensor 3: -0.0000005960	Sensor 4: -0.0000005960
Sensor 1: -0.0000005960	Sensor 2: -0.0000005960	Sensor 3: -0.0000005960	Sensor 4: -0.0000005960
...
```
with 
```
  adc.waitDRDY(); // wait for DRDY to go low before changing multiplexer register
  adc.setChannel(2,3);   // Set the MUX for differential between ch2 and 3 
  sensor1 = adc.readCurrentChannel(); // DOUT arriving here are from MUX AIN0 and AIN1

  adc.waitDRDY();
  adc.setChannel(4,5);
  sensor2 = adc.readCurrentChannel(); //// DOUT arriving here are from MUX AIN2 and AIN3

  adc.waitDRDY();
  adc.setChannel(6,7);
  sensor3 = adc.readCurrentChannel(); // DOUT arriving here are from MUX AIN4 and AIN5

  adc.waitDRDY();
  adc.setChannel(0,1); // switch back to MUX AIN0 and AIN1
  sensor4 = adc.readCurrentChannel(); // DOUT arriving here are from MUX AIN6 and AIN7

  //print the result.
  Serial.print("Sensor 1: ");
  Serial.print(sensor1,10);
  Serial.print("\t");
  Serial.print("Sensor 2: ");
  Serial.print(sensor2,10);
  Serial.print("\t");
  Serial.print("Sensor 3: ");
  Serial.print(sensor3,10);
  Serial.print("\t");
  Serial.print("Sensor 4: ");
  Serial.println(sensor4,10);
```
I tried to make an input but no reaktion.

i tranfsform with a logic level board from 5 to 3.3 volts. between adc and esp
i use the VSPI / SOFTWARE SPI because this is the Default SPI on ESP to use. Can be this a Problem?

**Comment by chepo92** [comment]
Maybe is not reading the SPI, all values are the same

**Comment by joba-1** [comment]
Hi @Trackhe, I have the same board that you show above and will try to make it work with an ESP32.

Not sure if you're still interested, but from the datasheet and the schematic that you provide it is clear you don't need a level shifter for the communication between ESP and ADS. They both use and work with ~3V just fine. Maybe you can try without level shifter and finally get some readings :)

I'll report progress here (if any) given that's ok @chepo92

**Comment by Trackhe** [comment]
Glad to hear, and yes i m very interested :)

**Comment by chepo92** [comment]
My two cents: https://github.com/ADS1xxx-Series-ADC-Libraries/ADS1255-ADS1256

**Comment by joba-1** [comment]
opened issue there... :)

https://github.com/ADS1xxx-Series-ADC-Libraries/ADS1255-ADS1256/issues/4

**Comment by Trackhe** [comment]
A port to esp-idf framework would be nice.

**Comment by joba-1** [comment]
Promised feedback: nice lib, works fine, thanks! I probably wouldn't pack floating point stuff and conversion functions in the same class when microcontrollers are the target, but that's an easy fix should I need it.
 
I don't know how to handle SPI with the ESP32 IDF which probably would be the major effort in porting it. Sorry, I did it with the Arduino framework. That worked hassle free (from the lib side - i did mess up the cabling due to the various levels of ESP32 pin numberings and SPI ports :) )
I used PlatformIO though, not the Arduino IDE. The only thing I needed to do was cloning the git repo in the lib directory of my PlatformIO project. In the library code no changes were required. I didn't try all examples, I just built my own on the basis of the 8x single ended one. Here is the code, just in case. One loop needs ~2.4ms, so without the delay it would be a little over 420Hz frequency for a 8-measurements-swipe, not bad - and it still includes the unneeded request for the current mux: 

```
#include <Arduino.h>

#include <ADS1256.h>
#include <SPI.h>

// Initialize ADS1256 object
ADS1256 adc(7.68, 2.5, false); // clockSpeed in Mhz,  VREF in volt, if use RESET PIN 

void setup()
{
  Serial.begin(115200);
  Serial.println("ADS1256 " __FILE__ " " __TIMESTAMP__);

  // Sending SDATAC to stop reading contionus data, so we can send other command
  adc.sendCommand(ADS1256_CMD_SDATAC);
  Serial.println("SDATAC command sent");
  
/*  Single Ended Mode
    ADS1256 support 8 single ended channel
    use setChannel(p) for this purpose, where p is the number of positive input channel between 0 and 7 (AIN0 to AIN7).
    AINCOM are automatically set as the negative input channel.
*/
  Serial.println("Changing channels for single ended mode.");
}

void loop() {
  long raw[8];
  unsigned char mux[8];

  for (int i = 0; i < sizeof(mux); ++i) {
    adc.setChannel(i);
    adc.waitDRDY();
    mux[i] = adc.readRegister(ADS1256_RADD_MUX);
    raw[i] = adc.readCurrentChannelRaw();
  }

  Serial.println();
  for (int i = 0; i < sizeof(mux); ++i) {
    long long millivolts = ((raw[i] - 1300LL) * 2780LL) / (4689000LL - 1300LL);
    Serial.printf("Channel[%d]: mux=0x%02x, adc=%ld, mV=%lld\n", i, mux[i], raw[i], millivolts);
  }

  delay(5000); // repeat once per 5 seconds
}

```
