### ISSUE TITLE
Arduino Uno Error

### ISSUE THREAD

**Issue by boromyr** [adienakhmad/ADS1256#5]
Hi, I can't use the library with Arduino Uno, I can compile the code only for Arduino Mega. Can pins for Arduino Uno be remapped? Thank you.

**Comment by adienakhmad** [comment]
There is a pull request that I haven't had the time to check and merge.
It is supposedly add compatibility for Arduino Uno.

You can see it in here
https://github.com/adienakhmad/ADS1256/pull/4/commits

**Comment by adienakhmad** [comment]
I've merged the pull request.
